import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// ReceiptScannerExpenses — generated by AppFactoryKit appgen from niche "receipt-expense".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum ReceiptScannerExpensesFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "ReceiptScannerExpenses",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "doc.viewfinder",
                          title: "ReceiptScannerExpenses",
                          message: "Scan receipts → categorized expense log."),
                    .init(systemImage: "doc.text.magnifyingglass",
                          title: "Go Pro",
                          message: "Unlimited receipts, export CSV, mileage.")
                ],
                presentsPaywallOnFinish: true,
                accent: .blue
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock ReceiptScannerExpenses Pro",
                subheadline: "Unlimited receipts, export CSV, mileage.",
                benefits: [
                    .init(systemImage: "infinity", title: "Unlimited receipts"),
                    .init(systemImage: "bolt.fill", title: "Export CSV"),
                    .init(systemImage: "nosign", title: "Mileage")
                ],
                productIDs: ["receipt-expense_yearly", "receipt-expense_weekly"],
                highlightedProductID: "receipt-expense_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .blue, heroSystemImage: "doc.viewfinder")
            )
        )
        return AppFactory(config)
    }
}

@main
struct ReceiptScannerExpensesApp: App {
    @StateObject private var factory = ReceiptScannerExpensesFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.blue)
        }
    }
}
